'use strict';
const KEY = 'bonjour-francais-progress-v1';
const categories = [['route','学习路线'],['pronunciation','发音'],['vocabulary','词汇'],['grammar','语法'],['listening','听力'],['speaking','口语'],['reading','阅读'],['writing','写作'],['review','错题与收藏'],['resources','官方资源'],['draws','EE 邀请记录']];
const descriptions = {pronunciation:'按课次查发音、连读与听辨',vocabulary:'词性、性数、搭配与辨析',grammar:'完整结构表、变位与中文讲解',listening:'每课教材音频的听力任务',speaking:'按情景提问、回应并复述',reading:'读对话与资料，核对信息',writing:'按课次完成短文与改错'};
const main = document.getElementById('main');
const {vocabulary,resources} = window.COURSE_CONTENT;
const catalog = window.COURSE_LIBRARY.catalog;
const lesson14 = {...catalog.find(c=>c.number===14), ...window.LESSON14_CONTENT,
  categorySections:{grammar:['faire','questions','jobs','time','verbs','errors'], vocabulary:['jobs','words'], pronunciation:['sound'], reading:['phrases'], speaking:['phrases'], writing:['phrases','errors']},
  listening:'听第 14 课教材录音：第一遍辨认人物与地点；第二遍记职业、居住地、工作地、星期、时刻与交通方式；第三遍核对 faire、est-ce que、省音和 jours / fois；第四遍分角色跟读并用 4—6 句复述安排。'};
const courses = new Map([...window.COURSE_LIBRARY.lessons,lesson14].map(c=>[c.number,c]));
for(const course of courses.values())if(!course.exercises)course.exercises=[...course.sections.find(s=>s.id==='practice').html.matchAll(/<h3>([A-J])\. (.*?)<\/h3>([\s\S]*?)(?=<h3>|$)/g)].map(([,id,title,body])=>({id,title,html:`<h3>${id}. ${title}</h3>${body}`}));
const questions = [...window.COURSE_CONTENT.questions.map(q=>({...q,lesson:14})),...Array.from(courses.values()).flatMap(c=>c.quickQuestions.map(q=>({...q,lesson:c.number})))];
const emptyState = () => ({version:1,completed:[],wrong:[],favorites:[],notes:{},attempts:{}});
function validState(s) {return s && s.version===1 && ['completed','wrong','favorites'].every(k=>Array.isArray(s[k])) && s.completed.every(n=>Number.isInteger(n)&&n>=1&&n<=36) && s.wrong.every(id=>questions.some(q=>q.id===id)) && s.favorites.every(n=>Number.isInteger(n)&&n>=1&&n<=36) && s.notes && typeof s.notes==='object' && !Array.isArray(s.notes) && Object.values(s.notes).every(v=>typeof v==='string') && s.attempts && typeof s.attempts==='object' && !Array.isArray(s.attempts);}
let state=emptyState(), storageAvailable=true;
try {const stored=JSON.parse(localStorage.getItem(KEY));if(validState(stored))state=stored;}catch {storageAvailable=false;}
function notify(message) {const el=document.getElementById('notice');el.textContent=message;el.classList.add('notice-visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('notice-visible'),3500);}
function save() {try {localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;return true;}catch {storageAvailable=false;notify('浏览器未能保存记录，请导出备份。');return false;}}
function escapeHtml(value) {return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function external(url,label) {return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)} ↗</a>`;}
function heading(k,title,description='') {return `<div class="eyebrow">${k}</div><h1>${title}</h1>${description?`<p class="subtle">${description}</p>`:''}`;}
function navigation(page) {const selected=Number(location.hash.split('/')[1]);const n=courses.has(selected)?selected:14;document.getElementById('navigation').innerHTML=categories.map(([id,label])=>`<a class="nav-link ${page===id?'active':''}" ${page===id?'aria-current="page"':''} href="#${id}${categories.slice(1,8).some(c=>c[0]===id)?'/'+n:''}">${label}</a>`).join('');}
function note(id,prompt) {return `<section class="section"><h2>${prompt}</h2><textarea data-note="${id}" aria-label="${prompt}" placeholder="写下自己的表达、问题或复习要点…">${escapeHtml(state.notes[id]||'')}</textarea><div class="print-note" data-print-note="${id}">${escapeHtml(state.notes[id]||'（尚未填写）')}</div><p class="source-note">输入后自动保存在当前浏览器，可在“学习记录与备份”中导出。</p></section>`;}
function quiz(list=questions) {return list.map(q=>`<form class="question" data-question="${q.id}"><div class="eyebrow">第 ${q.lesson||14} 课</div><h3>${escapeHtml(q.question)}</h3><div class="answer-options">${q.options.map((v,i)=>`<label><input type="radio" name="answer" value="${i}" required> ${escapeHtml(v)}</label>`).join('')}</div><button class="button secondary" type="submit">检查答案</button><div class="feedback" aria-live="polite"></div><p class="print-answer">答案：${escapeHtml(q.options[q.answer])}。${escapeHtml(q.explanation)}</p></form>`).join('');}
function route() {return heading('MA PETITE ROUTINE','今天，从第 14 课继续。','按教材前进，也给听、说、读、写留一点时间。')+`<section class="hero"><div><span class="tag">A1 · LEÇON 14</span><h2 lang="fr">À Londres</h2><p class="subtle">在伦敦 · 谈论职业与工作安排</p></div><a class="button light" href="#lesson/14">${state.completed.includes(14)?'回顾本课':'进入本课'} →</a></section><div class="two"><a class="card card-link" href="#review"><h3>复习一下</h3><p>${state.wrong.length} 道待复习错题 · ${state.favorites.length} 节收藏课程</p></a><div class="card"><h3>你自己的学习记录</h3><p>已标记完成 ${state.completed.length} / 36 课。课次完成记录由你确认。</p></div></div><section class="section"><div class="section-heading"><h2>所有学习分类</h2><span class="source-note">随时查，也能按课学</span></div><div class="grid">${categories.slice(1,8).map(([id,label],i)=>`<a class="card card-link" href="#${id}"><div class="card-number">0${i+1}</div><h3>${label} →</h3><p>${descriptions[id]}</p></a>`).join('')}</div></section><section class="section"><h2>走向 NCLC 7</h2><div class="roadmap"><div class="current">A1 教材学习<small>当前阶段</small></div><div>A2 巩固<small>后续补充</small></div><div>中级综合训练<small>听说读写</small></div><div>考试专项<small>按四项成绩核对 NCLC</small></div></div><p class="source-note">课程完成记录用于安排学习。语言等级通过对应评估或考试成绩确认。</p></section><section class="section"><h2>前 14 课 · 教材路线</h2><div class="course-list">${catalog.map(c=>`<a class="card card-link" href="#lesson/${c.number}"><span class="tag">${String(c.number).padStart(2,'0')} · ${courses.has(c.number)?'详细讲义':'待补充'}</span><h3>${escapeHtml(c.title)} · ${escapeHtml(c.translation)} →</h3><p>${escapeHtml(c.core.join(' · '))}</p></a>`).join('')}</div></section><section class="section"><h2>A1 课次记录</h2><p class="source-note">${Array.from(courses.keys()).sort((a,b)=>a-b).map(n=>`第 ${n} 课`).join('、')}已提供详细讲义。其余课次正在逐课补充，可先保留教材笔记。</p><div class="lessons">${Array.from({length:36},(_,i)=>i+1).map(n=>`<a href="#lesson/${n}" class="lesson-link ${n===14?'current':''} ${state.completed.includes(n)?'done':''}" aria-label="第 ${n} 课${state.completed.includes(n)?'，已完成':''}">${String(n).padStart(2,'0')}${state.completed.includes(n)?' ✓':''}</a>`).join('')}</div></section>`;}
function knowledge(ids,course=lesson14) {
  const wanted=ids||course.sections.map(s=>s.id);
  return `<div class="lesson-notes">${wanted.map(id=>{const section=course.sections.find(s=>s.id===id);return `<section class="knowledge-section" id="lesson${course.number}-${id}" aria-labelledby="title-${course.number}-${id}">${section.html.replace('<h2>',`<h2 id="title-${course.number}-${id}">`)}</section>`;}).join('')}</div>`;
}
function writtenPractice(letters,course=lesson14) {return `<section class="lesson-notes knowledge-section"><h2>书面练习与参考答案</h2><p class="subtle">先在笔记中作答，再展开答案核对。</p>${course.exercises.filter(e=>letters.includes(e.id)).map(e=>e.html).join('')}</section>`;}
function quickCheck(list,n=14) {const qs=list||questions.filter(q=>q.lesson===n);return `<section class="section" id="lesson${n}-quick-check"><h2>即时小测 · ${qs.length} 题</h2><p class="subtle">提交后查看解析，答错的题会自动进入“错题与收藏”。开放任务请按参考答案和自查标准检查。</p>${quiz(qs)}</section>`;}
function lesson(n) {
  const course=courses.get(n),meta=catalog.find(c=>c.number===n),done=state.completed.includes(n),favorite=state.favorites.includes(n);
  const qs=questions.filter(q=>q.lesson===n);
  return heading(`LEÇON ${String(n).padStart(2,'0')}`,meta?`${escapeHtml(meta.title)} · ${escapeHtml(meta.translation)}`:`第 ${n} 课 · 教材学习记录`,course?`详细复习讲义 · ${course.sections.length} 个模块 · ${course.exercises.length} 组书面练习与解析 · ${qs.length} 道即时小测`:'本课详细讲义正在补充；可以先结合教材记录笔记。')+
  `<div class="toolbar"><button class="button" data-complete="${n}">${done?'已完成 ✓ · 撤销':'标记本课完成'}</button><button class="button secondary" data-favorite="${n}">${favorite?'已收藏 ★ · 取消':'收藏本课'}</button><a href="#route">回到学习路线</a></div>`+
  (course?`<div class="toolbar lesson-actions"><button class="button secondary" data-print>打印 / 另存为 PDF（含答案）</button><button class="button secondary" data-answers="open">展开全部参考答案</button><button class="button secondary" data-answers="close">收起全部参考答案</button></div><nav class="lesson-toc" aria-label="第 ${n} 课知识目录"><h2>本课目录</h2><div>${course.sections.map(section=>`<a href="#lesson/${n}/${section.id}">${escapeHtml(section.title.replace(' / ',' · '))}</a>`).join('')}<a href="#lesson/${n}/quick-check">即时小测 · ${qs.length} 题</a></div></nav>`+knowledge(course.sections.filter(s=>s.id!=='review').map(s=>s.id),course)+quickCheck(qs,n)+knowledge(['review'],course)+`<section class="section"><h2>按技能继续练习</h2><div class="grid">${['listening','speaking','reading','writing'].map(id=>`<a class="card card-link" href="#${id}/${n}"><h3>${categories.find(c=>c[0]===id)[1]} →</h3><p>第 ${n} 课 · ${descriptions[id]}</p></a>`).join('')}</div></section>`:'')+note(`lesson-${n}`,'本课笔记');
}
function categoryPage(kind,arg) {
  const n=arg===undefined?14:Number(arg),course=courses.get(n),label=categories.find(c=>c[0]===kind)[1];
  if(!course)return heading('A1',label)+`<div class="empty">第 ${escapeHtml(arg)} 课的详细内容正在补充。<p><a href="#${kind}/14">查看第 14 课 →</a></p></div>`;
  let html=heading(`A1 · LEÇON ${String(n).padStart(2,'0')}`,label,`${escapeHtml(course.title)} · ${escapeHtml(course.translation)}`)+`<div class="toolbar"><label>选择课次 <select id="course-select" data-category="${kind}">${Array.from(courses.values()).sort((a,b)=>a.number-b.number).map(c=>`<option value="${c.number}" ${n===c.number?'selected':''}>第 ${c.number} 课 · ${escapeHtml(c.title)}</option>`).join('')}</select></label><a href="#lesson/${n}">查看本课完整讲义 →</a></div>`;
  const sectionMap=course.categorySections;
  if(kind==='listening')html+=`<section class="knowledge-section"><h2>第 ${n} 课音频 · 听辨、核对与复述</h2><p>${external(resources[4][2],'打开出版方配套音频与视频')}，按手中教材的课次和音轨编号找到录音。</p><p>${escapeHtml(course.listening)}</p><h3>复听记录</h3><p>写下第一遍确定的信息、第二遍补上的信息、对照原文后发现的错误，以及准备模仿的两句话。每次跟读时先听整句，再暂停复述。</p></section>`+knowledge(sectionMap.pronunciation,course);
  else html+=knowledge(sectionMap[kind],course);
  const groups={grammar:['A','B','D','I'],vocabulary:['C'],pronunciation:['H'],reading:['G'],speaking:['E','J'],writing:['F','I']};
  if(groups[kind])html+=writtenPractice(groups[kind],course);
  const qs=questions.filter(q=>q.lesson===n&&(q.group===kind||(kind==='grammar'&&!q.group)));
  if(qs.length)html+=quickCheck(qs,n);
  if(['listening','speaking','reading','writing'].includes(kind))html+=note(n===14?kind:`${kind}-${n}`,`第 ${n} 课 · 我的${label}练习`);
  return html;
}
let drawData=null,drawLoading=false,drawError=false,drawType='',drawYear='',drawPage=0;
async function loadDraws() {if(drawData||drawLoading)return;drawLoading=true;try {const response=await fetch('data/draws.json');if(!response.ok)throw Error('无法读取邀请记录');const data=await response.json();if(!Array.isArray(data.rounds))throw Error('数据格式错误');drawData=data;}catch {drawError=true;}finally {drawLoading=false;if(location.hash==='#draws')render();}}
function draws() {loadDraws();const header=heading('EXPRESS ENTRY','EE 邀请记录','从官方记录观察轮次、类别、最低获邀 CRS 分数与邀请数量。');if(!drawData)return header+`<div class="empty">${drawError?'记录暂时无法读取，请稍后重试或查看官方页面。':'正在读取官方记录…'}</div><p>${external(resources[2][2],'打开 IRCC 官方邀请页面')}</p>`;const all=drawData.rounds,types=[...new Set(all.map(r=>r.category))].sort(),years=[...new Set(all.map(r=>r.date.slice(0,4)))].sort().reverse();const filtered=all.filter(r=>(!drawType||r.category===drawType)&&(!drawYear||r.date.startsWith(drawYear)));drawPage=Math.max(0,Math.min(drawPage,Math.max(0,Math.ceil(filtered.length/20)-1)));const shown=filtered.slice(drawPage*20,drawPage*20+20);const recent=filtered.slice(0,12).reverse();return header+`<p class="source-note">最近成功检查：${escapeHtml(drawData.checked_at||'尚未检查')} · ${all.length} 条历史记录 · 时间保留官方 UTC</p><div class="toolbar"><label>类别 <select id="draw-type"><option value="">全部类别</option>${types.map(t=>`<option ${drawType===t?'selected':''} value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join('')}</select></label><label>年份 <select id="draw-year"><option value="">全部年份</option>${years.map(y=>`<option ${drawYear===y?'selected':''}>${y}</option>`).join('')}</select></label><button class="button secondary" id="french-only">只看法语类别</button></div>${drawType&&recent.length?`<section class="card"><h3>所选类别 · 最近 ${recent.length} 轮最低 CRS</h3><div class="chart" role="img" aria-label="${escapeHtml(recent.map(r=>r.date+'：'+r.crs).join('；'))}">${recent.map(r=>`<div class="bar-item">${r.crs}<div class="bar" style="height:${Math.round(r.crs/1200*110)}px"></div>${escapeHtml(r.date.slice(5))}</div>`).join('')}</div></section>`:''}<div class="table-scroll section"><table><thead><tr><th>轮次</th><th>日期 / UTC 时间</th><th>类别</th><th>最低 CRS</th><th>邀请数量</th><th>详情</th></tr></thead><tbody>${shown.map(r=>`<tr><td>#${r.id}</td><td>${escapeHtml(r.date)}<br><small>${escapeHtml(r.time||'')}</small></td><td>${escapeHtml(r.category)}</td><td>${r.crs}</td><td>${r.invitations.toLocaleString('zh-CN')}</td><td>${external(r.source,'官方')}<details><summary>同分排序</summary>${escapeHtml(r.tie_breaking||'官网未提供')}</details></td></tr>`).join('')||'<tr><td colspan="6">没有符合筛选条件的记录。</td></tr>'}</tbody></table></div><div class="pager"><button class="button secondary" data-page="-1" ${drawPage===0?'disabled':''}>上一页</button><span>${drawPage+1} / ${Math.max(1,Math.ceil(filtered.length/20))} · ${filtered.length} 条</span><button class="button secondary" data-page="1" ${(drawPage+1)*20>=filtered.length?'disabled':''}>下一页</button></div><p class="source-note">首版记录联邦 EE 轮次，包括 EE 中的 PNP 专属轮次。各省独立邀请另行记录。以每轮官方详情为核对来源。</p>`;}
function settings() {return heading('MES DONNÉES','学习记录与备份','保留你自己的学习痕迹。')+`<div class="card prose"><h2>当前浏览器中的记录</h2><p>${state.completed.length} 课完成记录 · ${state.wrong.length} 道错题 · ${Object.keys(state.notes).length} 份笔记</p><p>更换浏览器、清除网站数据或迁移网站地址前，请导出备份。备份文件包含你的个人笔记，请保存在自己的电脑上。</p><div class="toolbar"><button class="button" id="export">导出学习记录</button><label class="button secondary">导入备份<input id="import" type="file" accept="application/json,.json" hidden></label></div></div>`;}
function render() {const [page,arg,section]=(location.hash.slice(1)||'route').split('/');navigation(page==='lesson'?'route':page);document.getElementById('search').value='';if(page==='route')main.innerHTML=route();else if(page==='lesson'){const n=Number(arg);main.innerHTML=Number.isInteger(n)&&n>=1&&n<=36?lesson(n):heading('','找不到这节课');}else if(categories.slice(1,8).some(c=>c[0]===page))main.innerHTML=categoryPage(page,arg);else if(page==='review')main.innerHTML=heading('RÉVISION','错题与收藏','答对的错题会从待复习列表中移除。')+`<section class="section"><h2>收藏课程</h2>${state.favorites.length?state.favorites.map(n=>`<p><a href="#lesson/${n}">第 ${n} 课${catalog.find(c=>c.number===n)?' · '+escapeHtml(catalog.find(c=>c.number===n).title):''} →</a></p>`).join(''):'<p class="subtle">在课程页面点击“收藏本课”。</p>'}</section><section class="section"><h2>待复习错题</h2>${state.wrong.length?quiz(questions.filter(q=>state.wrong.includes(q.id))):'<div class="empty">目前没有待复习错题。继续学一课吧。<p><a href="#lesson/14">进入 À Londres →</a></p></div>'}</section>`;else if(page==='resources')main.innerHTML=heading('RESSOURCES','官方资源','学习标准、教材资源与加拿大官方信息。')+`<div class="links">${resources.map(r=>`<div class="card">${external(r[2],r[0])}<p class="subtle">${r[1]}</p></div>`).join('')}</div>`;else if(page==='draws')main.innerHTML=draws();else if(page==='settings')main.innerHTML=settings();else main.innerHTML=heading('','找不到这个页面')+'<a href="#route">返回学习路线</a>';if(section&&page==='lesson')document.getElementById(`lesson${Number(arg)}-${section}`)?.scrollIntoView();if(!storageAvailable)main.insertAdjacentHTML('afterbegin','<p role="alert">浏览器存储暂不可用，学习记录可能无法保留，请及时导出备份。</p>');}
main.addEventListener('submit',e=>{const form=e.target.closest('[data-question]');if(!form)return;e.preventDefault();const q=questions.find(q=>q.id===form.dataset.question),value=new FormData(form).get('answer');if(value===null)return;const correct=Number(value)===q.answer;state.attempts[q.id]=correct;state.wrong=state.wrong.filter(id=>id!==q.id);if(!correct)state.wrong.push(q.id);save();const feedback=form.querySelector('.feedback');feedback.className=`feedback ${correct?'correct':'wrong'}`;feedback.textContent=(correct?'答对了。':'再想一想。正确答案：'+q.options[q.answer]+(/[.!?。！？]$/.test(q.options[q.answer])?' ':'。'))+q.explanation;});
main.addEventListener('input',e=>{if(e.target.dataset.note){state.notes[e.target.dataset.note]=e.target.value;const printed=main.querySelector(`[data-print-note="${e.target.dataset.note}"]`);if(printed)printed.textContent=e.target.value||'（尚未填写）';save();}});
main.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.hasAttribute('data-print'))window.print();if(button.dataset.answers){main.querySelectorAll('.lesson-notes details').forEach(d=>d.open=button.dataset.answers==='open');}if(button.dataset.complete){const n=Number(button.dataset.complete);state.completed=state.completed.includes(n)?state.completed.filter(v=>v!==n):[...state.completed,n];save();render();}if(button.dataset.favorite){const n=Number(button.dataset.favorite);state.favorites=state.favorites.includes(n)?state.favorites.filter(v=>v!==n):[...state.favorites,n];save();render();}if(button.dataset.page){drawPage+=Number(button.dataset.page);render();}if(button.id==='french-only'){drawType=drawData?.rounds.find(r=>r.category==='法语能力类别')?.category||'';drawPage=0;render();}if(button.id==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bonjour-francais-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
main.addEventListener('change',async e=>{if(e.target.id==='course-select'){location.hash=`#${e.target.dataset.category}/${e.target.value}`;return;}if(e.target.id==='draw-type'){drawType=e.target.value;drawPage=0;render();}if(e.target.id==='draw-year'){drawYear=e.target.value;drawPage=0;render();}if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try {if(file.size>5_000_000)throw Error('备份文件过大');const imported=JSON.parse(await file.text());if(!validState(imported))throw Error('这不是有效的学习记录备份');if(!confirm('导入将替换当前浏览器中的学习记录，是否继续？'))return;state=imported;save();render();notify('学习记录已导入');}catch(error){notify(error.message);}}});
document.getElementById('search').addEventListener('input',e=>{const term=e.target.value.trim().toLocaleLowerCase();if(!term){render();return;}const entries=[...categories.slice(1,8).map(([id,label])=>[label,descriptions[id],`#${id}`]),...vocabulary.map(v=>[v[0],v[1]+' '+v[2],'#vocabulary']),...resources.map(r=>[r[0],r[1],'#resources']),...Array.from(courses.values()).flatMap(c=>c.sections.map(s=>[`第 ${c.number} 课 · ${s.title}`,plainText(s.html),`#lesson/${c.number}/${s.id}`])),...catalog.map(c=>[`${c.title} ${c.translation}`,`第${c.number}课 `+c.core.join(' '),`#lesson/${c.number}`])];const matches=entries.filter(r=>(r[0]+' '+r[1]).toLocaleLowerCase().includes(term));main.innerHTML=heading('RECHERCHE','搜索结果')+`<p class="subtle">${matches.length} 项匹配</p><div class="links">${matches.map(r=>`<a class="card card-link" href="${r[2]}"><h3>${escapeHtml(r[0])} →</h3><p>${escapeHtml(searchExcerpt(r[1],term))}</p></a>`).join('')||'<div class="empty">没有找到匹配内容，试试“职业”“时间”或“faire”。</div>'}</div>`;});
function plainText(html) {return html.replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();}
function searchExcerpt(text,term) {const found=text.toLocaleLowerCase().indexOf(term);const start=Math.max(0,found-35);return (start?'…':'')+text.slice(start,start+140)+(text.length>start+140?'…':'');}
// In-page lesson navigation preserves selected answers and opened reference panels.
window.addEventListener('hashchange',e=>{
  const from=(e.oldURL||'').split('#')[1]||'',to=location.hash.slice(1);
  const previous=from.split('/'),next=to.split('/');
  if(previous[0]==='lesson'&&next[0]==='lesson'&&previous[1]===next[1]&&next[2]&&!document.getElementById('search').value){document.getElementById(`lesson${Number(next[1])}-${next[2]}`)?.scrollIntoView();return;}
  window.scrollTo(0,0);render();
});
let printPanels=[];
window.addEventListener('beforeprint',()=>{printPanels=[...main.querySelectorAll('details')].map(panel=>({panel,open:panel.open}));printPanels.forEach(({panel})=>panel.open=true);});
window.addEventListener('afterprint',()=>{printPanels.forEach(({panel,open})=>panel.open=open);printPanels=[];});
render();
