'use strict';
const KEY = 'bonjour-francais-progress-v1';
const categories = [['route','学习路线'],['pronunciation','发音'],['vocabulary','词汇'],['grammar','语法'],['listening','听力'],['speaking','口语'],['reading','阅读'],['writing','写作'],['review','错题与收藏'],['resources','官方资源'],['draws','EE 邀请记录']];
const descriptions = {pronunciation:'听辨、连读和发音要点',vocabulary:'职业、工作与时间表达',grammar:'faire、提问和时间介词',listening:'配套音频与听力任务',speaking:'介绍职业，询问工作安排',reading:'用短文检验理解',writing:'把所学写成自己的句子'};
const main = document.getElementById('main');
const {vocabulary,questions,resources} = window.COURSE_CONTENT;
const emptyState = () => ({version:1,completed:[],wrong:[],favorites:[],notes:{},attempts:{}});
function validState(s) {return s && s.version===1 && ['completed','wrong','favorites'].every(k=>Array.isArray(s[k])) && s.completed.every(n=>Number.isInteger(n)&&n>=1&&n<=36) && s.wrong.every(id=>questions.some(q=>q.id===id)) && s.favorites.every(n=>Number.isInteger(n)&&n>=1&&n<=36) && s.notes && typeof s.notes==='object' && !Array.isArray(s.notes) && Object.values(s.notes).every(v=>typeof v==='string') && s.attempts && typeof s.attempts==='object' && !Array.isArray(s.attempts);}
let state=emptyState(), storageAvailable=true;
try {const stored=JSON.parse(localStorage.getItem(KEY));if(validState(stored))state=stored;}catch {storageAvailable=false;}
function notify(message) {const el=document.getElementById('notice');el.textContent=message;el.classList.add('notice-visible');clearTimeout(notify.timer);notify.timer=setTimeout(()=>el.classList.remove('notice-visible'),3500);}
function save() {try {localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;return true;}catch {storageAvailable=false;notify('浏览器未能保存记录，请导出备份。');return false;}}
function escapeHtml(value) {return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function external(url,label) {return `<a href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(label)} ↗</a>`;}
function heading(k,title,description='') {return `<div class="eyebrow">${k}</div><h1>${title}</h1>${description?`<p class="subtle">${description}</p>`:''}`;}
function navigation(page) {document.getElementById('navigation').innerHTML=categories.map(([id,label])=>`<a class="nav-link ${page===id?'active':''}" ${page===id?'aria-current="page"':''} href="#${id}">${label}</a>`).join('');}
function note(id,prompt) {return `<section class="section"><h2>${prompt}</h2><textarea data-note="${id}" aria-label="${prompt}" placeholder="写下自己的表达、问题或复习要点…">${escapeHtml(state.notes[id]||'')}</textarea><p class="source-note">输入后自动保存在当前浏览器，可在“学习记录与备份”中导出。</p></section>`;}
function quiz(list=questions) {return list.map(q=>`<form class="question" data-question="${q.id}"><h3>${escapeHtml(q.question)}</h3><div class="answer-options">${q.options.map((v,i)=>`<label><input type="radio" name="answer" value="${i}" required> ${escapeHtml(v)}</label>`).join('')}</div><button class="button secondary" type="submit">检查答案</button><div class="feedback" aria-live="polite"></div></form>`).join('');}
function route() {return heading('MA PETITE ROUTINE','今天，从第 14 课继续。','按教材前进，也给听、说、读、写留一点时间。')+`<section class="hero"><div><span class="tag">A1 · LEÇON 14</span><h2 lang="fr">À Londres</h2><p class="subtle">在伦敦 · 谈论职业与工作安排</p></div><a class="button light" href="#lesson/14">${state.completed.includes(14)?'回顾本课':'进入本课'} →</a></section><div class="two"><a class="card card-link" href="#review"><h3>复习一下</h3><p>${state.wrong.length} 道待复习错题 · ${state.favorites.length} 节收藏课程</p></a><div class="card"><h3>你自己的学习记录</h3><p>已标记完成 ${state.completed.length} / 36 课。课次完成记录由你确认。</p></div></div><section class="section"><div class="section-heading"><h2>所有学习分类</h2><span class="source-note">随时查，也能按课学</span></div><div class="grid">${categories.slice(1,8).map(([id,label],i)=>`<a class="card card-link" href="#${id}"><div class="card-number">0${i+1}</div><h3>${label} →</h3><p>${descriptions[id]}</p></a>`).join('')}</div></section><section class="section"><h2>走向 NCLC 7</h2><div class="roadmap"><div class="current">A1 教材学习<small>当前阶段</small></div><div>A2 巩固<small>后续补充</small></div><div>中级综合训练<small>听说读写</small></div><div>考试专项<small>按四项成绩核对 NCLC</small></div></div><p class="source-note">课程完成记录用于安排学习。语言等级通过对应评估或考试成绩确认。</p></section><section class="section"><h2>A1 课次记录</h2><p class="source-note">第 14 课提供本站补充讲解与练习，其余课次可以记录教材学习和笔记。</p><div class="lessons">${Array.from({length:36},(_,i)=>i+1).map(n=>`<a href="#lesson/${n}" class="lesson-link ${n===14?'current':''} ${state.completed.includes(n)?'done':''}" aria-label="第 ${n} 课${state.completed.includes(n)?'，已完成':''}">${String(n).padStart(2,'0')}${state.completed.includes(n)?' ✓':''}</a>`).join('')}</div></section>`;}
function grammar() {return `<div class="prose"><section class="card"><h2>用 faire 询问活动或职业</h2><p>询问职业可以说 <span lang="fr">Qu’est-ce que vous faites dans la vie ?</span>。回答时直接用 être 加职业名词，通常省略冠词。</p><div class="example" lang="fr">Je suis informaticienne. <span class="translation" lang="zh">我是信息技术从业者。</span></div><p lang="fr">je fais · tu fais · il/elle fait · nous faisons · vous faites · ils/elles font</p></section><section class="card section"><h2>问什么、哪里、什么时候</h2><p><span lang="fr">Qu’est-ce que…</span> 问“什么”；<span lang="fr">Où est-ce que…</span> 问“哪里”；<span lang="fr">Quand est-ce que…</span> 问“什么时候”。</p><div class="example"><p lang="fr">Où est-ce que vous travaillez ?</p><p class="translation">您在哪里工作？</p><p lang="fr">Quand est-ce que vous rentrez ?</p><p class="translation">您什么时候回来？</p></div></section><section class="card section"><h2>把时间表达完整</h2><p><span lang="fr">du lundi au vendredi</span>：从星期一到星期五。<span lang="fr">le lundi</span>：习惯性的每个星期一。<span lang="fr">une semaine</span> 可以直接表示停留时长。</p><div class="example"><p lang="fr">Je travaille du lundi au vendredi.</p><p class="translation">我从周一工作到周五。</p></div></section></div>`;}
function vocab() {return `<div class="table-scroll"><table><thead><tr><th>法语</th><th>中文</th><th>原创例句</th></tr></thead><tbody>${vocabulary.map(v=>`<tr><td lang="fr">${v[0]}</td><td>${v[1]}</td><td lang="fr">${v[2]}</td></tr>`).join('')}</tbody></table></div>`;}
function reading() {return `<div class="card prose"><span class="tag">原创补充短文</span><p class="french" lang="fr">Camille est informaticienne. Elle travaille à Londres du lundi au mercredi. Le jeudi, elle travaille à Paris. Elle rentre chez elle vendredi soir.</p><details><summary>查看中文解释</summary><p>Camille 是信息技术从业者。她周一至周三在伦敦工作，周四在巴黎工作，周五晚上回家。</p></details><h3 class="section">读后任务</h3><p>Camille 从事什么职业？她哪几天在伦敦？她什么时候回家？请用法语各写一句。</p></div>`+note('reading','写下你的回答');}
function learningTask(kind) {if(kind==='listening')return `<div class="card prose"><h2>用教材配套音频练习</h2><p>${external(resources[4][2],'打开出版方配套音频与视频')}</p><ol class="checklist"><li>找到与你的教材第 14 课对应的音轨，第一遍只抓住人物和地点。</li><li>第二遍记录职业、星期和时间表达。</li><li>对照教材核对，选两句暂停跟读。</li></ol></div>`+note('listening','记录听到的词与需要再听的句子');if(kind==='speaking')return `<div class="card prose"><h2>说一段你自己的工作安排</h2><ol class="checklist"><li>用三句话介绍职业、工作地点和工作时间。</li><li>回答：Qu’est-ce que vous faites dans la vie ?</li><li>回答：Où est-ce que vous travaillez ? Quand est-ce que vous rentrez ?</li></ol><p>先说，再检查职业名词、动词变位和时间介词。可以用电脑录音工具留存自己的练习。</p></div>`+note('speaking','记录你的口语提纲');if(kind==='writing')return `<div class="card prose"><h2>写一段简短的自我介绍</h2><p>用 4—6 句话介绍职业、工作地点和一周安排。试着使用 <span lang="fr">faire、du… au…、le lundi</span>。</p><p class="subtle">自查：主语与动词是否一致？时间表达是否完整？介绍职业时是否正确使用冠词？</p></div>`+note('writing','我的短文');return `<div class="card prose"><h2>听辨与跟读提示</h2><p><span lang="fr">Londres</span> 的读音是 /lɔ̃dʁ/：/ɔ̃/ 是鼻化元音，不把字母 n 单独读成一个音。</p><p>在 <span lang="fr">vous êtes</span> 中，vous 的 s 连读成 /z/；在 <span lang="fr">vous faites</span> 中，f 是辅音，不做这种连读。</p><p>打开教材配套音频，模仿整句节奏，再读出自己的句子。</p><p>${external(resources[4][2],'教材配套音频')}</p></div>`;}
function lesson(n) {const done=state.completed.includes(n),favorite=state.favorites.includes(n);return heading(`LEÇON ${String(n).padStart(2,'0')}`,n===14?'À Londres · 在伦敦':`第 ${n} 课 · 教材学习记录`,n===14?'配合教材学习：介绍职业，询问活动，表达工作时间。本站例句与练习为原创补充。':'结合手中的教材学习，并记录自己的问题与收获。')+`<div class="toolbar"><button class="button" data-complete="${n}">${done?'已完成 ✓ · 撤销':'标记本课完成'}</button><button class="button secondary" data-favorite="${n}">${favorite?'已收藏 ★ · 取消':'收藏本课'}</button><a href="#route">回到学习路线</a></div>`+(n===14?`<section class="card"><h2>本课的小目标</h2><ul class="checklist"><li>介绍职业和工作地点。</li><li>使用 faire 的现在时和 est-ce que 提问。</li><li>用 du… au… 表达一段时间。</li></ul></section><section class="section"><h2>核心词汇</h2>${vocab()}</section><section class="section"><h2>中文讲解</h2>${grammar()}</section><section class="section"><h2>练一练</h2>${quiz()}</section><section class="section"><h2>听说读写</h2><div class="grid">${['listening','speaking','reading','writing'].map(id=>`<a class="card card-link" href="#${id}"><h3>${categories.find(c=>c[0]===id)[1]} →</h3><p>${descriptions[id]}</p></a>`).join('')}</div></section>`:'')+note(`lesson-${n}`,'本课笔记');}
let drawData=null,drawLoading=false,drawError=false,drawType='',drawYear='',drawPage=0;
async function loadDraws() {if(drawData||drawLoading)return;drawLoading=true;try {const response=await fetch('data/draws.json');if(!response.ok)throw Error('无法读取邀请记录');const data=await response.json();if(!Array.isArray(data.rounds))throw Error('数据格式错误');drawData=data;}catch {drawError=true;}finally {drawLoading=false;if(location.hash==='#draws')render();}}
function draws() {loadDraws();const header=heading('EXPRESS ENTRY','EE 邀请记录','从官方记录观察轮次、类别、最低获邀 CRS 分数与邀请数量。');if(!drawData)return header+`<div class="empty">${drawError?'记录暂时无法读取，请稍后重试或查看官方页面。':'正在读取官方记录…'}</div><p>${external(resources[2][2],'打开 IRCC 官方邀请页面')}</p>`;const all=drawData.rounds,types=[...new Set(all.map(r=>r.category))].sort(),years=[...new Set(all.map(r=>r.date.slice(0,4)))].sort().reverse();const filtered=all.filter(r=>(!drawType||r.category===drawType)&&(!drawYear||r.date.startsWith(drawYear)));drawPage=Math.max(0,Math.min(drawPage,Math.max(0,Math.ceil(filtered.length/20)-1)));const shown=filtered.slice(drawPage*20,drawPage*20+20);const recent=filtered.slice(0,12).reverse();return header+`<p class="source-note">最近成功检查：${escapeHtml(drawData.checked_at||'尚未检查')} · ${all.length} 条历史记录 · 时间保留官方 UTC</p><div class="toolbar"><label>类别 <select id="draw-type"><option value="">全部类别</option>${types.map(t=>`<option ${drawType===t?'selected':''} value="${escapeHtml(t)}">${escapeHtml(t)}</option>`).join('')}</select></label><label>年份 <select id="draw-year"><option value="">全部年份</option>${years.map(y=>`<option ${drawYear===y?'selected':''}>${y}</option>`).join('')}</select></label><button class="button secondary" id="french-only">只看法语类别</button></div>${drawType&&recent.length?`<section class="card"><h3>所选类别 · 最近 ${recent.length} 轮最低 CRS</h3><div class="chart" role="img" aria-label="${escapeHtml(recent.map(r=>r.date+'：'+r.crs).join('；'))}">${recent.map(r=>`<div class="bar-item">${r.crs}<div class="bar" style="height:${Math.round(r.crs/1200*110)}px"></div>${escapeHtml(r.date.slice(5))}</div>`).join('')}</div></section>`:''}<div class="table-scroll section"><table><thead><tr><th>轮次</th><th>日期 / UTC 时间</th><th>类别</th><th>最低 CRS</th><th>邀请数量</th><th>详情</th></tr></thead><tbody>${shown.map(r=>`<tr><td>#${r.id}</td><td>${escapeHtml(r.date)}<br><small>${escapeHtml(r.time||'')}</small></td><td>${escapeHtml(r.category)}</td><td>${r.crs}</td><td>${r.invitations.toLocaleString('zh-CN')}</td><td>${external(r.source,'官方')}<details><summary>同分排序</summary>${escapeHtml(r.tie_breaking||'官网未提供')}</details></td></tr>`).join('')||'<tr><td colspan="6">没有符合筛选条件的记录。</td></tr>'}</tbody></table></div><div class="pager"><button class="button secondary" data-page="-1" ${drawPage===0?'disabled':''}>上一页</button><span>${drawPage+1} / ${Math.max(1,Math.ceil(filtered.length/20))} · ${filtered.length} 条</span><button class="button secondary" data-page="1" ${(drawPage+1)*20>=filtered.length?'disabled':''}>下一页</button></div><p class="source-note">首版记录联邦 EE 轮次，包括 EE 中的 PNP 专属轮次。各省独立邀请另行记录。以每轮官方详情为核对来源。</p>`;}
function settings() {return heading('MES DONNÉES','学习记录与备份','保留你自己的学习痕迹。')+`<div class="card prose"><h2>当前浏览器中的记录</h2><p>${state.completed.length} 课完成记录 · ${state.wrong.length} 道错题 · ${Object.keys(state.notes).length} 份笔记</p><p>更换浏览器、清除网站数据或迁移网站地址前，请导出备份。备份文件包含你的个人笔记，请保存在自己的电脑上。</p><div class="toolbar"><button class="button" id="export">导出学习记录</button><label class="button secondary">导入备份<input id="import" type="file" accept="application/json,.json" hidden></label></div></div>`;}
function render() {const [page='route',arg]=location.hash.slice(1).split('/');navigation(page==='lesson'?'route':page);document.getElementById('search').value='';if(page==='route')main.innerHTML=route();else if(page==='lesson'){const n=Number(arg);main.innerHTML=Number.isInteger(n)&&n>=1&&n<=36?lesson(n):heading('','找不到这节课');}else if(page==='grammar')main.innerHTML=heading('A1 · À LONDRES','语法','先理解，再用自己的例句检验。')+grammar()+`<section class="section"><h2>检验理解</h2>${quiz(questions.slice(0,4))}</section>`;else if(page==='vocabulary')main.innerHTML=heading('A1 · À LONDRES','词汇','把职业、动词和时间一起记。')+vocab();else if(page==='reading')main.innerHTML=heading('A1 · À LONDRES','阅读')+reading();else if(['pronunciation','listening','speaking','writing'].includes(page))main.innerHTML=heading('A1 · À LONDRES',categories.find(c=>c[0]===page)[1])+learningTask(page);else if(page==='review')main.innerHTML=heading('RÉVISION','错题与收藏','答对的错题会从待复习列表中移除。')+`<section class="section"><h2>收藏课程</h2>${state.favorites.length?state.favorites.map(n=>`<p><a href="#lesson/${n}">第 ${n} 课${n===14?' · À Londres':''} →</a></p>`).join(''):'<p class="subtle">在课程页面点击“收藏本课”。</p>'}</section><section class="section"><h2>待复习错题</h2>${state.wrong.length?quiz(questions.filter(q=>state.wrong.includes(q.id))):'<div class="empty">目前没有待复习错题。继续学一课吧。<p><a href="#lesson/14">进入 À Londres →</a></p></div>'}</section>`;else if(page==='resources')main.innerHTML=heading('RESSOURCES','官方资源','学习标准、教材资源与加拿大官方信息。')+`<div class="links">${resources.map(r=>`<div class="card">${external(r[2],r[0])}<p class="subtle">${r[1]}</p></div>`).join('')}</div>`;else if(page==='draws')main.innerHTML=draws();else if(page==='settings')main.innerHTML=settings();else main.innerHTML=heading('','找不到这个页面')+'<a href="#route">返回学习路线</a>';if(!storageAvailable)main.insertAdjacentHTML('afterbegin','<p role="alert">浏览器存储暂不可用，学习记录可能无法保留，请及时导出备份。</p>');}
main.addEventListener('submit',e=>{const form=e.target.closest('[data-question]');if(!form)return;e.preventDefault();const q=questions.find(q=>q.id===form.dataset.question),value=new FormData(form).get('answer');if(value===null)return;const correct=Number(value)===q.answer;state.attempts[q.id]=correct;state.wrong=state.wrong.filter(id=>id!==q.id);if(!correct)state.wrong.push(q.id);save();const feedback=form.querySelector('.feedback');feedback.className=`feedback ${correct?'correct':'wrong'}`;feedback.textContent=(correct?'答对了。':'再想一想。正确答案：'+q.options[q.answer]+'。')+q.explanation;});
main.addEventListener('input',e=>{if(e.target.dataset.note){state.notes[e.target.dataset.note]=e.target.value;save();}});
main.addEventListener('click',e=>{const button=e.target.closest('button');if(!button)return;if(button.dataset.complete){const n=Number(button.dataset.complete);state.completed=state.completed.includes(n)?state.completed.filter(v=>v!==n):[...state.completed,n];save();render();}if(button.dataset.favorite){const n=Number(button.dataset.favorite);state.favorites=state.favorites.includes(n)?state.favorites.filter(v=>v!==n):[...state.favorites,n];save();render();}if(button.dataset.page){drawPage+=Number(button.dataset.page);render();}if(button.id==='french-only'){drawType=drawData?.rounds.find(r=>r.category==='法语能力类别')?.category||'';drawPage=0;render();}if(button.id==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='bonjour-francais-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}});
main.addEventListener('change',async e=>{if(e.target.id==='draw-type'){drawType=e.target.value;drawPage=0;render();}if(e.target.id==='draw-year'){drawYear=e.target.value;drawPage=0;render();}if(e.target.id==='import'){const file=e.target.files[0];if(!file)return;try {if(file.size>5_000_000)throw Error('备份文件过大');const imported=JSON.parse(await file.text());if(!validState(imported))throw Error('这不是有效的学习记录备份');if(!confirm('导入将替换当前浏览器中的学习记录，是否继续？'))return;state=imported;save();render();notify('学习记录已导入');}catch(error){notify(error.message);}}});
document.getElementById('search').addEventListener('input',e=>{const term=e.target.value.trim().toLocaleLowerCase();if(!term){render();return;}const entries=[...categories.slice(1,8).map(([id,label])=>[label,descriptions[id],`#${id}`]),...vocabulary.map(v=>[v[0],v[1]+' '+v[2],'#vocabulary']),...resources.map(r=>[r[0],r[1],'#resources']),['À Londres 在伦敦','第14课 职业 faire 时间介词','#lesson/14']];const matches=entries.filter(r=>(r[0]+' '+r[1]).toLocaleLowerCase().includes(term));main.innerHTML=heading('RECHERCHE','搜索结果')+`<p class="subtle">${matches.length} 项匹配</p><div class="links">${matches.map(r=>`<a class="card card-link" href="${r[2]}"><h3>${escapeHtml(r[0])} →</h3><p>${escapeHtml(r[1])}</p></a>`).join('')||'<div class="empty">没有找到匹配内容，试试“职业”“时间”或“faire”。</div>'}</div>`;});
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
render();
