"""Bundle authored lesson JSON as static JS; metadata is not completed teaching content."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
catalog = json.loads((ROOT / 'lessons/catalog.json').read_text(encoding='utf-8'))
lessons = []
for entry in catalog:
    source = ROOT / 'lessons' / f"{entry['number']:02}.json"
    if source.exists():
        data = json.loads(source.read_text(encoding='utf-8'))
        assert data['number'] == entry['number']
        lessons.append({**entry, **data})
content = {'catalog': catalog, 'lessons': lessons}
(ROOT / 'course.js').write_text('// Generated by scripts/build-course.py from lessons/*.json.\nwindow.COURSE_LIBRARY = ' + json.dumps(content, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Bundled {len(lessons)} authored lessons; lesson 14 loads from its existing module.')

# Content fingerprints avoid showing a cached, older course bundle after publishing.
import hashlib
import re
index = ROOT / 'index.html'
page = index.read_text(encoding='utf-8')
for asset in ['styles.css', 'content.js', 'course.js', 'lesson14.js', 'app.js']:
    digest = hashlib.sha256((ROOT / asset).read_bytes()).hexdigest()[:12]
    page = re.sub(r'(["\'])' + re.escape(asset) + r'(?:\?v=[a-f0-9]+)?(["\'])',
                  lambda match: match[1] + asset + '?v=' + digest + match[2], page)
index.write_text(page, encoding='utf-8')
