"""Bundle authored lesson JSON as static JS; metadata is not completed teaching content."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent
catalog = json.loads((ROOT / 'lessons/catalog.json').read_text(encoding='utf-8'))
lessons = []
for entry in catalog:
    source = ROOT / 'lessons' / f"{entry['number']:02}.json"
    if source.exists():
        data = json.loads(source.read_text(encoding='utf-8'))
        assert data['number'] == entry['number']
        lessons.append({**entry, **data})
content = {'catalog': catalog, 'lessons': lessons}
(ROOT / 'course.js').write_text('// Generated by scripts/build-course.py from lessons/*.json.\nwindow.COURSE_LIBRARY = ' + json.dumps(content, ensure_ascii=False, indent=2) + ';\n', encoding='utf-8')
print(f'Bundled {len(lessons)} authored lessons; lesson 14 loads from its existing module.')
